# Generated by Django 5.0 on 2026-10-03 20:24

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('url_name', models.CharField(blank=True, max_length=100)),
                ('is_menu', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.activity')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_node', to='auth.group')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organisationchart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRUDPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('states', models.JSONField(blank=True, default=list)),
                ('row_condition', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.activity')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.organisationchart')),
            ],
            options={
                'unique_together': {('activity', 'organisation')},
            },
        ),
    ]
