# Generated by Django 5.0 on 2026-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateInTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text='Django model label, for example clinic.Visit', max_length=100)),
                ('state', models.CharField(max_length=40)),
                ('display_name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['model_label', 'state'],
                'unique_together': {('model_label', 'state')},
            },
        ),
        migrations.CreateModel(
            name='StateNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(default='clinic.visit', max_length=100)),
                ('from_state', models.CharField(max_length=40)),
                ('to_state', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('model_label', 'from_state', 'to_state')},
            },
        ),
    ]
