# Generated by Django 5.0 on 2026-10-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpredictedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EMERGENCY', 'Emergency arrival'), ('ABSENCE', 'Staff absence'), ('EQUIPMENT', 'Equipment failure'), ('OVERRUN', 'Procedure overrun')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.proceduresession')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
