# Generated by Django 5.0 on 2026-10-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='Main clinic', max_length=120)),
                ('scheduled_at', models.DateTimeField()),
                ('current_state', models.CharField(choices=[('BOOKED', 'Booked'), ('CHECK_IN', 'Checked in'), ('TRIAGE', 'Triage'), ('IN_EXAM', 'In examination'), ('PROCEDURE', 'Procedure'), ('RECOVERY', 'Recovery'), ('DISCHARGE', 'Discharge'), ('BILLED', 'Billed')], default='BOOKED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], default='DOG', max_length=8)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='clinic.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('planned_minutes', models.PositiveSmallIntegerField(default=30)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('vet_confirmed_completion', models.BooleanField(default=False)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clinic.procedure')),
            ],
        ),
    ]
